on:
push:
	  branches:
		- main
	workflow_dispatch:
  
  jobs:
	run_pull:
	  name: Run pull
	  runs-on: ubuntu-latest
	  
	  steps:
		- name: Install SSH keys
		  run: |
			install -m 600 -D /dev/null ~/.ssh/id_rsa
			echo "${{ secrets.key_path}}" > ~/.ssh/id_rsa
			ssh-keyscan -H 20.205.139.3 >> ~/.ssh/known_hosts
			
		- name: Connect and pull
		  run: |
			ssh ${{ secrets.alpha }}@$20.205.139.3 "cd ${{ secrets.work_dir }} && git checkout ${{ secrets.main_branch }} && git pull && exit"
			
		- name: Cleanup
		  run: rm -rf ~/.ssh
  
