name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Adding Known Hosts
        run: ssh-keyscan -H 20.205.139.33 >> ~/.ssh/known_hosts

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.key_path }}

      - name: Deploy to VM (using encrypted SSH key)
        uses: appleboy/ssh-action@master
        with:
          host: 20.205.139.33
          username: ${{ secrets.falpha_username }}
          key: ${{ secrets.key_path }}
          script: |
            # Navigate to the backend-api directory
            cd backend-api

            # Install dependencies
            npm install

            # Start the application
            npm start
